### ISSUE TITLE
model's checkpoints on Kinetics for testing

### ISSUE THREAD

**Issue by qianhanxuan** [DeLightCMU/ElaborativeRehearsal#11]
Thanks for your impressive work! 

Recently, I tried to re-implement this work with your official codebase, following the same training/test protocols as in this codebase. However, the results on Kinetics I got were lower than the results reported in the paper, as shown below.
<img width="537" alt="image" src="https://user-images.githubusercontent.com/28927949/159108029-dcd042c3-a5fd-42d7-bb09-f59435339321.png">

I'm trying to find out why this happened. Could you release the model's checkpoints used for testing on Kinetics? This will help me a lot. 

Looking forward to your reply, thanks!

**Comment by zzzhhh1031** [comment]
How did you get the kinetics dataset mentioned in the paper?

**Comment by cshizhe** [comment]
Hi, please find the checkpoints of ER-ZSAR Full model [here](https://www.dropbox.com/sh/3bo5zlpqeyphi2z/AAD77G_Am2pAEF4XGyp2fI3Aa?dl=0).

**Comment by cshizhe** [comment]
> How did you get the kinetics dataset mentioned in the paper?

Kinetics dataset is not introduced by our paper. We only split the original dataset for ZSAR. You should download the dataset from Youtube.
