### ISSUE TITLE
Elaborative Descriptions 

### ISSUE THREAD

**Issue by jxrloveyou** [DeLightCMU/ElaborativeRehearsal#12]
Is there any code for crawling EDs?

**Comment by cshizhe** [comment]
We mainly use wikipedia and online dictionary. 
This tool can crawl wikipedia items: https://pypi.org/project/wikipedia/

**Comment by jxrloveyou** [comment]
@cshizhe Hello, glad to get your reply. I used this tool to crawl the description and found that it is not the same as the description you crawl.
For example apply eye makeup has this error in the Wikipedia tool: wikipedia.exceptions.PageError: Page id "apple eye makeup" does not match any pages. Try another id!
I don't get what you describe in your paper.

**Comment by cshizhe** [comment]
As mentioned in the paper, the EDs are manually annotated. To accelerate the annotation speed, we crawl descriptions from wikipedia and online dictionaries. When there are no wikipedia pages, only the dictionary descriptions are used. The annotators can select or rewrite these descriptions.
