### ISSUE TITLE
About release the collected EDs publicly

### ISSUE THREAD

**Issue by zhiyiGao** [DeLightCMU/ElaborativeRehearsal#2]
Thanks for your great work. But why only release Elaborative Descriptions on the Kinetics dataset？We also would like the Elaborative Descriptions of HMDB51，UCF101，and Olympic Sports. Looking forward to your reply.

**Comment by cshizhe** [comment]
Thanks for your interests in our work. We have just uploaded EDs for the three datasets on dataset folder.
