### ISSUE TITLE
Pretrained model link broken

### ISSUE THREAD

**Issue by Atharva-Chandak** [DeLightCMU/ElaborativeRehearsal#4]
The link for pretrained model for kinetics dataset seems to broken. Can you please check that? 
Also, could you kindly release the pretrained models for the other three datasets as well?

**Comment by cshizhe** [comment]
Hi, we use the pretrained TSM model in this [repo](https://github.com/mit-han-lab/temporal-shift-module). They might update the link.

**Comment by cshizhe** [comment]
Updated the link in the script.
