### ISSUE TITLE
About the Kinetics datasets.

### ISSUE THREAD

**Issue by haoranD** [DeLightCMU/ElaborativeRehearsal#6]
Dear authors,

Thanks for this amazing work, and we are very interested in it.

I am a bit confused, to run the code:
` bash scripts/extract_tsm_features.sh '0,1,2' `

1. Shall we download the Kinetics dataset ourselves and extract them into images?
2. Can you please give any hints about 'we obtain 220 new action classes outside of Kinetics-400 after cleaning'?

We are very grateful for your help!

Best Wishes.

**Comment by cshizhe** [comment]
Hi, you should download the videos from Youtube. Here is a [toolkit](https://github.com/jremmons/ActivityNet/blob/master/Crawler/Kinetics/download.py) for downloading.
We select 220 new action classes in Kinetics-600 outside of Kinetics-400 by checking the action names and video ids.

**Comment by haoranD** [comment]
Many thanks for the quick reply, I will try now and maybe back if I got problems.

Thanks a lot again.
